# Generated by Django 4.2.2 on 2023-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(max_length=60)),
                ('cs', models.CharField(max_length=500)),
                ('delta_cs', models.CharField(max_length=150)),
                ('match_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=60)),
                ('region', models.CharField(default='na1', max_length=60)),
            ],
        ),
    ]
